export const UPDATE_MOVIES = "UPDATE_MOVIES";
export const UPDATE_AUTH = "UPDATE_AUTH";
export const UPDATE_FILTER = "UPDATE_FILTER";
export const UPDATE_PAGINATION = "UPDATE_PAGINATION";
export const FETCHING_MOVIES = "FETCHING_MOVIES";
export const ERROR_GET_MOVIES = "ERROR_GET_MOVIES";
export const LOGOUT = "LOGOUT";
