export const UPDATE_AUTH = "UPDATE_AUTH";
export const LOGOUT = "LOGOUT";
export const TOGGLE_LOGIN_MODAL = "TOGGLE_LOGIN_MODAL";
export const UPDATE_FAVORITE_MOVIES = "UPDATE_FAVORITE_MOVIES";
export const FETCH_REQUEST_AUTH = "FETCH_REQUEST_AUTH";
export const FETCH_SUCCESS_AUTH = "FETCH_SUCCESS_AUTH";
export const FETCH_ERROR_AUTH = "FETCH_ERROR_AUTH";
