export const FETCH_SUCCESS_AUTH = "FETCH_SUCCESS_AUTH";
export const LOGOUT = "LOGOUT";
export const TOGGLE_MODAL_LOGIN = "TOGGLE_MODAL_LOGIN";
export const UPDATE_FAVORITES = "UPDATE_FAVORITES";
export const UPDATE_WATCHLIST = "UPDATE_WATCHLIST";
export const FETCH_REQUEST_AUTH = "FETCH_REQUEST_AUTH";
export const FETCH_ERROR_AUTH = "FETCH_ERROR_AUTH";
